### ISSUE TITLE
original systematic review for the PTSD dataset

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/systematic-review-datasets#14]
It turns out there is a discrepancy of 4 inclusions between the ptsd-dataset in this repo (38 inclusions) and the systematic review we linked it to (34 inclusions). 

 For the ptsd dataset, up until now we refer to https://doi.org/10.1080/00273171.2017.1412293, a systematic review (1) reporting 34 inclusions. It turns out that the `.ris` files in the [corresponding osf-page](https://osf.io/4hqk6/) contain 38 inclusions.

This number belongs to another systematic review (2) (on the same dataset), http://dx.doi.org/10.1080/10705511.2016.1247646. On the corresponding osf-page, https://osf.io/6vdfk/ however, there are no `.ris` files uploaded (yet). 

I think we have refer to one or the other paper. For the 34 inclusions paper we need to update the dataset by recoding the 4 inclusions to exclusions (see comment by @J535D165 below). For the paper with 38 inclusions, the osf-page should be updated (@Rensvandeschoot), and all information in the documentation on systematic review 1 should be replaced with information on systematic review 2.   

Any thoughts?

------------------------------------------------------------------

Thanks @terrymyc! Thanks for your contribution. 

A couple of additions and remarks are listed below:

## ~Exclude 4 more papers~

~Based on the paper, the team excluded 4 more papers. 34 of the 38 papers were described in the paper. The papers listed below have to be excluded (isn't it? @Rensvandeschoot @GerbrichFerdinands ): ~

- ~Sterling, M., Hendrikz, J., & Kenardy, J. (2010). Compensation claim lodgement and health outcome developmental trajectories following whiplash injury: A prospective study. Pain, 150(1), 22-28.~
- ~Hou, W. K., Law, C. C., Yin, J., & Fu, Y. T. (2010). Resource Loss, Resource Gain, and Psychological Resilience and Dysfunction Following Cancer Diagnosis: A Growth Mixture Modeling Approach. Health Psychology, 29(5), 484-495. doi:10.1037/a0020809~
- ~Mason, S. T., Corry, N., Gould, N. F., Amoyal, N., Gabriel, V., Wiechman-Askay, S., . . . Fauerbach, J. A. (2010). Growth curve trajectories of distress in burn patients. Journal of Burn Care and Research, 31(1), 64-72. doi:10.1097/BCR.0b013e3181cb8ee6~
- ~Pérez, S., Conchado, A., Andreu, Y., Galdón, M. J., Cardeña, E., Ibáñez, E., & Durá, E. (2016). Acute stress trajectories 1 year after a breast cancer diagnosis. Supportive Care in Cancer, 24(4), 1671-1678. doi:10.1007/s00520-015-2960-x~

## Connect to RIS files on OSF

The RIS files are now available on OSF. Can you connect them to your code and remove the ones in the Github repository?

## Count duplicates

Thanks for your statistics so far. Can you count the number of duplicate items as well? Please don't make things too complicated, count check of duplicate abstracts for example. 

It turns out that @qubixes is also doing some work on the dataset statistics. This is implemented in an extension for asreview https://github.com/asreview/asreview-statistics. It might be interesting to have a look. It would be nice to integrate the functionality with this repo (not for now).

_Originally posted by @J535D165 in https://github.com/asreview/systematic-review-datasets/pull/13#issuecomment-595120977_

**Comment by GerbrichFerdinands** [comment]
Also, if we start referring to the review with 38 inclusions, can we still call it the `ptsd` dataset, or should it become `grolts`?

**Comment by Rensvandeschoot** [comment]
@GerbrichFerdinands: thank you for raising this issue!

So, there are two papers and two OSF repositories:

1. The [GROLTS paper ](https://doi.org/10.1080/10705511.2016.1247646) with 38 inclusions - OSF [https://osf.io/vw3t7/](https://osf.io/vw3t7/). This was the first paper we have written based on the search.

2. The [paper in MBR](https://doi.org/10.1080/00273171.2017.1412293) in which we decided to exclude 4 papers because of a stricter definition of 'traumatic event' - OSF [https://osf.io/vk4be/](https://osf.io/vk4be/)

Both are the same PTSD data, so I would still call it PTSD in your documentation.

**Comment by GerbrichFerdinands** [comment]
Thank you for clearing up! 

I believe this issue is then closed by PR #13 by @terrymyc, where paper 2 with 34 inclusions has been replaced by paper 1 with 38 inclusions. 

However, it might be nice to link to this issue in the .readme, what do you think? Or is this confusing? I am thinking of adding something like this:

> Note that this dataset is also used for a [different systematic review paper](https://www-tandfonline-com.proxy.library.uu.nl/doi/full/10.1080/00273171.2017.1412293), see issue #14.

**Comment by Rensvandeschoot** [comment]
good idea! will you do so? then, I'll close this issue
