### ISSUE TITLE
wilson dataset - 1/3 of abstracts is missing

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/systematic-review-datasets#15]
About 1/3 of the abstracts in the wilson dataset is missing (of which 3 inclusions). 

![image](https://user-images.githubusercontent.com/45358236/75978099-136eca80-5ede-11ea-8d8e-ccdd8744ac48.png)

I think it would be worthwhile to see if we could figure out what causes this missingness. 
One of the authors (Dr. Hannah Ewald) named the following possible causes:

> 572/1090 missing abstracts are from the years 1912 to 1989. 

 > The rest comes from both Embase and Medline and I can’t see any systematic error (i.e. there is mixed page numbers, all names from A to Z, all indexed as journal articles, different languages and journals). Although it’s odd in such a high number, maybe they just don’t have abstracts. 

I am awaiting response from the first author (dr. Christian Appenzeller-Herzog) who is currently out of office.

**Comment by J535D165** [comment]
@terrymyc, can you add statistics to this workflow (in a separate PR)?

And can you make a graph in the notebook with the missing abstracts over time? A bar chart or line chart for example.

**Comment by terrymyc** [comment]
> @terrymyc, can you add statistics to this workflow (in a separate PR)?
> 
> And can you make a graph in the notebook with the missing abstracts over time? A bar chart or line chart for example.

Yes, I'll work on it.
