### ISSUE TITLE
Inconsistent names label columns

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/systematic-review-datasets#73]
The column with labels does not have the same name over all datasets. 

- In the Kwok data the label is `final_included` (see cell 8 in [this notebook](https://github.com/asreview/systematic-review-datasets/blob/master/datasets/Kwok_2020/process_Kwok_dataset.ipynb)),
- It looks like that most datasets have a label column called `label_included`. For example in the Cohen datasets (see cell 4 in [this notebook](https://github.com/asreview/systematic-review-datasets/blob/master/datasets/Cohen_2006/process_Cohen_datasets_online.ipynb).

Maybe there are more variations, but I didn't find them this far. 

Then, the README of this repo says the following: 

> To indicate labelling decisions, one can use "included" or "label_included". The latter label called "included" is needed to indicate the final included publications in the simulations. 

It would be nice to make the name of the label column more consistent throughout all datasets.

**Comment by terrymyc** [comment]
I see the label in the Kwok dataset is `label_included`?
